if (isDedicated) exitWith {};

private ["_templateVEH"];

_templateVEH = [
    ["ATV квадроцикл", "ATV_US_EP1"],
    ["Шакал", "BAF_Jackal2_L2A1_W"],
    ["HMMWV ExA OIF", "ExA_HMMWV_M2_USMC_W"],
    ["HMMWV M2+ASK(ExA)", "ExA_HMMWV_M2_A1"],
	["HMMWV", "pzn_gc_us_HMMWV"],
	["HMMWV M240", "pzn_gc_us_HMMWV_Armored"],
	["HMMWV M2", "pzn_gc_us_HMMWV_M2"],
    ["RG-31", "ExA_RG31_M2_OD"],
    ["===========", ""],
	["M113", "ACE_M113A3"],
    ["AAV Калоша", "AAV"],
    ["LAV-25A2", "LAV25"],
	["M2A2 Bradley", "ACE_M2A2_W"],
    ["M2A3 Bradley", "ACE_M2A3_W"],
    ["Stryker m2", "ACE_Stryker_ICV_M2"],
    ["Stryker mk19", "ACE_Stryker_ICV_MK19"],
    ["Stryker mgs", "ACE_Stryker_ICV_MKGS"],
    ["M60A3", "tu_M60A3_USMC"],
	["M1A1 Abrams", "ACE_M1A1_NATO"],
	["M1A1 Abrams TUSK", "ACE_M1A1HC_TUSK"],
    ["===========", ""],
    ["Apache Longbow", "TU_AH64D"],
    ["CH-47F Chinook", "CH_47F_black"],
    ["UH-1H Iroquois", "UH1H_US"],
	["UH60 BlackHawk", "UH60M_EP1"],
	["UH-1Y Venom", "UH1Y"],
	["AH-1W Cobra", "ACE_AH1W_TOW_W"],
    ["===========", ""],
    ["F-35A Lightning", "TU_F45A_BMB"],
	["A-10", "TU_A10C_6BMB"],
    ["C-130J Super Hercules", "C130J_US_EP1"],
    ["F-A-18A (BMB)", "TU_FA18A_BMB"],
    ["AV-8B Harrier Multirole", "TU_AV8B_MP"],
    ["CH-53D Sea Stallion", "tu_ch53"],
    ["MV-22 Osprey", "MV22"],
    ["AH11 Уайлдкет", "AW159_Lynx_BAF"],
    ["НСЗ Мерлин", "BAF_Merlin_HC3_D"],
    ["AH6J Little Bird Magnum P.I.", "AH6J_EP1_SMD_MAGPI"],
    ["Mirage США","SMAF_MF1_AGRESSOR_BLUE"],
    ["Mirage ЧСО","SMAF_MF1_CDF_CAS"],
    ["===========", ""],
    ["Zodiac", "Zodiac"],
    ["RHIB M2", "RHIB"],
    ["Малая лодка", "Smallboat_2"],
    ["Рыбацкая лодка", "Fishing_Boat"]
    ["===========", ""],
    ["Икарус", "Ikarus_SMD_OPENDAYZ"],
    ["SUV", "SUV_SMD_BLOPS"],
    ["SUV - M134", "ArmoredSUV_PMC"],
    ["===========", ""],
    ["УАЗ", "UAZ_RU"],
	["УАЗ ДШКМ", "tu_dshk_uaz"],
	["УАЗ СПГ9", "tu_spg9_uaz"],
	["Урал", "ACE_Ural_RU_D"],
	["БРДМ-2", "tu_brdm2"],
	["БТР-70", "ACE_BTR70_RU"],
	["БМП-2", "ACE_BMP2_RU"],
	["Т-72Б", "ACE_T72B_RU"],
	["Т-80У", "tsg_t80u_2"],
	["МИ-8МТ", "tu_mi8mt"],
	["МИ-8МТВ(НАР)", "Mi17_rockets_RU_24"],
	["МИ-24В", "tu_mi24V"],
	["СУ-25СМ", "TU_Su25SM_250_S8"],
    ["Ан-2 Кукурузник", "An2_TK_EP1"],
    ["ИЛ-76", "il76loaded"]
];

_VenTypeSel = (_templateVEH select (_this select 0)) select 1;
_unit = _VenTypeSel createVehicle (_this select 1);
